package mobilebackup

import (
	"bytes"
	"context"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"testing"
)

func TestTLVStructuralGoldenRepeatsUnknownAndOwnership(t *testing.T) {
	// Arrange: literal independent 4/4/bytes fixture, not generated by this decoder.
	input, err := hex.DecodeString("000000060000000361626300000006000000026465ffffffff00000001660000000700000000")
	if err != nil {
		t.Fatal(err)
	}
	original := append([]byte(nil), input...)
	// Act.
	result, err := ParseTLV(context.Background(), input)
	// Assert: repeated/unknown tags preserved, own buffers independent, no serialization.
	if err != nil || len(result.Fields) != 4 || result.Fields[0].Tag != 6 || result.Fields[1].Tag != 6 || result.Fields[2].Tag != 0xffffffff || string(result.Fields[1].Value) != "de" || len(result.Fields[3].Value) != 0 {
		t.Fatal("TLV structure lost", err)
	}
	serialized, _ := json.Marshal(result)
	if string(serialized) != "{}" || fmt.Sprintf("%#v", result) != "mobile backup TLV [redacted]" {
		t.Fatal("TLV exposed")
	}
	result.Fields[0].Value[0] = 'x'
	if !bytes.Equal(input, original) {
		t.Fatal("TLV aliases input")
	}
	owned := result.Fields[0].Value
	result.Clear()
	if result.Fields != nil || !bytes.Equal(owned, make([]byte, len(owned))) {
		t.Fatal("owned TLV bytes retained")
	}
}
func TestTLVRejectsMalformedWholeStreamAndBounds(t *testing.T) {
	valid, _ := hex.DecodeString("0000000600000003616263")
	overflow, _ := hex.DecodeString("000000067fffffff")
	for _, input := range [][]byte{nil, valid[:7], valid[:10], append(append([]byte(nil), valid...), 1), overflow, make([]byte, (256<<10)+1), bytes.Repeat(make([]byte, 8), 1025)} {
		// Act / Assert: no successful prefix survives.
		result, err := ParseTLV(context.Background(), input)
		if !errors.Is(err, ErrTLV) || result.Fields != nil {
			t.Fatal("malformed TLV accepted")
		}
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if result, err := ParseTLV(ctx, valid); !errors.Is(err, ErrTLV) || result.Fields != nil {
		t.Fatal("cancelled TLV accepted")
	}
}
func FuzzTLVBounds(f *testing.F) {
	f.Add([]byte{0, 0, 0, 6, 0, 0, 0, 1, 'x'})
	f.Fuzz(func(t *testing.T, input []byte) {
		result, err := ParseTLV(context.Background(), input)
		if err != nil {
			if result.Fields != nil {
				t.Fatal("partial result")
			}
			return
		}
		if len(result.Fields) > 1024 {
			t.Fatal("field budget bypass")
		}
		total := 0
		for _, field := range result.Fields {
			total += 8 + len(field.Value)
		}
		if total != len(input) || total > 256<<10 {
			t.Fatal("TLV length mismatch")
		}
		result.Clear()
	})
}
